FROM registry.access.redhat.com/ubi9 AS doris-build-base

ARG PRODUCT_VERSION=3.0.3-rc04
ARG JAVA_VERSION=8

# install system requirements
RUN <<EOT
    # https://adoptium.net/en-GB/installation/linux/#_centosrhelfedora_instructions
    cat <<EOF > /etc/yum.repos.d/adoptium.repo
[Adoptium]
name=Adoptium
baseurl=https://packages.adoptium.net/artifactory/rpm/${DISTRIBUTION_NAME:-$(. /etc/os-release; echo $ID)}/\$releasever/\$basearch
enabled=1
gpgcheck=1
gpgkey=https://packages.adoptium.net/artifactory/api/gpg/key/public
EOF

    dnf update -y --setopt=install_weak_deps=False
    dnf install -y --setopt=install_weak_deps=False \
        bzip2 \
        gzip \
        hostname \
        jq \
        maven-openjdk${JAVA_VERSION} \
        nodejs \
        patch \
        perl-CPAN \
        pkg-config \
        tar \
        temurin-${JAVA_VERSION}-jdk \
        tzdata-java \
        which \
        unzip \
        wget \
        xz

    dnf clean all
    rm -rf /var/cache/yum
EOT

ENV JAVA_HOME=/usr/lib/jvm/temurin-${PRODUCT_VERSION}-jdk \
    JAVA_VERSION=${PRODUCT_VERSION}

# setup python3
RUN ln -s /usr/bin/python3 /usr/bin/python

WORKDIR /build

# download doris
# Download doris https://github.com/apache/doris/archive/refs/tags/3.0.3-rc04.tar.gz
RUN <<EOF
    mkdir -p /build/doris
    pushd /build/doris
    curl -sSLf https://github.com/apache/doris/archive/refs/tags/${PRODUCT_VERSION}.tar.gz \
        | tar -xz --strip-components=1
    popd

    # Add `set -x` after `set -euo pipefail`
    sed -i '/set -eo pipefail/a set -x' /build/doris/build.sh
    sed -i '/set -eo pipefail/a set -x' /build/doris/thirdparty/build-thirdparty.sh
EOF

# download thirdparty
RUN <<EOF
    pushd /build/doris/thirdparty
    ./download-thirdparty.sh
    popd
EOF

# patch doris submodule sha
RUN <<EOF
    set -ex
    # Patch submodules
    # get tag sha
    tag_sha=$(curl -s -H "Accept: application/vnd.github.v3.raw" "https://api.github.com/repos/apache/doris/git/ref/tags/${PRODUCT_VERSION}" | jq -r '.object.sha')
    # get submodule sha from tag sha
    # apache-orc: be/src/apache-orc
    # clucene: be/src/clucene
    submodule_apache_orc_sha=$(curl -s -H "Accept: application/vnd.github.v3.raw" "https://api.github.com/repos/apache/doris/git/trees/${tag_sha}?recursive=1" | jq -r '.tree[] | select(.path == "be/src/apache-orc") | .sha')
    submodule_clucene_sha=$(curl -s -H "Accept: application/vnd.github.v3.raw" "https://api.github.com/repos/apache/doris/git/trees/${tag_sha}?recursive=1" | jq -r '.tree[] | select(.path == "be/src/clucene") | .sha')

    pushd /build/doris
    # Patch build.sh submodule sha
    sed -i "s|/refs/heads/orc.tar.gz|/${submodule_apache_orc_sha}/orc.tar.gz|" build.sh
    sed -i "s|/refs/heads/clucene.tar.gz|/${submodule_clucene_sha}/clucene.tar.gz|" build.sh
    popd
EOF

# install build requirements
RUN <<EOF
    dnf update -y --setopt=install_weak_deps=False
    dnf install -y --setopt=install_weak_deps=False \
        automake \
        autoconf \
        bzip2 \
        cmake \
        diffutils \
        git \
        libcurl-devel \
        libtool \
        make \
        zlib-devel \

    microdnf clean all
    rm -rf /var/cache/yum

    # smoke test
    java -version
EOF

#########################################################################################
# setup ldb-toolchain
# Download ldb_toolchain_gen.aarch64.sh
# https://github.com/amosbird/ldb_toolchain_gen/releases/download/v0.9.1/ldb_toolchain_gen.aarch64.sh
# or https://github.com/amosbird/ldb_toolchain_gen/releases/download/v0.9.1/ldb_toolchain_gen.sh
# Note:
#   - In 0.9.1, ldb-toolchain containes curl, it conflicts with the system curl,
#     when use it, it will cause dns resolution error
#   - In 0.21, ldb-toolchain containes curl, it will verify the certificate
#     file /etc/ssl/certs/ca-certificates.crt. But ca-certificates package generate a default
#     file /etc/ssl/certs/ca-bundle.crt, so we need to create a symlink to fix it.
#   - 0.14.1 aaarch64 version is error to build doris
RUN <<EOF
    ARCH=$(uname -m)
    ARCH=${ARCH/arm64/aarch64}

    release_file="ldb_toolchain_gen.sh"
    if [ "$ARCH" == "aarch64" ]; then
        release_file="ldb_toolchain_gen.aarch64.sh"
    fi

    mkdir -p /build/ldb-toolchain
    pushd /build/ldb-toolchain
    curl -sSLf https://github.com/amosbird/ldb_toolchain_gen/releases/download/v${LDB_TOOLCHAIN_VERSION}/${release_file} \
        -o ldb_toolchain_gen.sh

    chmod +x ldb_toolchain_gen.sh

    ./ldb_toolchain_gen.sh /opt/ldb-toolchain

    ln -s /opt/ldb-toolchain/bin/bison /opt/ldb-toolchain/bin/byacc
    popd

    # fix /opt/ldb-toolchain/bin/curl certificate verify failed
    ln -s /etc/ssl/certs/ca-bundle.crt /etc/ssl/certs/ca-certificates.crt

    # cleanup
    rm -rf /build/ldb-toolchain
EOF

ENV PATH=/opt/ldb-toolchain/bin:$PATH
